Setting up cypress and jest tests and their coverage
pesto-students/babitz-frontend pull request #11
Opened 2021-07-21 19:27 UTC by siddanand

2021-07-25 14:36 UTC, chirgjn requested changes
Can we remove the Cypress examples, I don't think they're relevant to the project.

2021-07-25 14:36 UTC, chirgjn commented on pages/index.js
> -import Head from 'next/head'
Can you check if these changes are still imposed by `prettier`? We have changed our config so these might need to be reverted.

2021-07-25 14:36 UTC, chirgjn commented on package.json
> +    "coverage:report": "nyc report --check-coverage --statements 100",
```suggestion
    "coverage:report": "nyc report --check-coverage --statements 50",
```

2021-07-25 19:54 UTC, siddanand commented on .babelrc
> +}
For jest and cypress test

2021-07-25 19:54 UTC, siddanand commented on __tests__/HomeTest.js
> +});
A sample test case

2021-07-25 19:54 UTC, siddanand commented on cypress.json
> +}
For cypress coverage

2021-07-25 19:55 UTC, siddanand commented on cypress/fixtures/example.json
> +}
Pre-Installed with cypress

2021-07-25 19:55 UTC, siddanand commented on cypress/integration/home.spec.js
> +});
Sample test case for cypress

2021-07-25 19:56 UTC, siddanand commented on package.json
> +    "coverage:report": "nyc report --check-coverage --statements 50",
Scripts for cypress and jest

2021-07-26 09:46 UTC, chirgjn requested changes

2021-07-26 09:46 UTC, chirgjn commented on cypress.json
> +  }
```suggestion
```

2021-07-26 09:46 UTC, chirgjn commented on cypress/fixtures/example.json
> +}
Let's remove it

2021-07-26 09:46 UTC, chirgjn commented on __mocks__/fileMock.js
> +module.exports = "placeholder-file";
Can you add some reference link here

2021-07-26 09:46 UTC, chirgjn commented on __mocks__/styleMock.js
> +module.exports = {};
Can you add some reference link here

2021-07-26 13:01 UTC, siddanand commented on __mocks__/fileMock.js
> +module.exports = "placeholder-file";
https://circleci.com/blog/next-testing/

2021-07-27 12:32 UTC, chirgjn approved these changes

2021-07-27 12:42 UTC, merged