Update README.md
pesto-students/babitz-frontend pull request #15
Opened 2021-07-22 23:00 UTC by siddanand

2021-07-24 14:09 UTC, chirgjn requested changes

2021-07-24 14:09 UTC, chirgjn commented on README.md
> +This is a [Next.js](https://nextjs.org/) project.
```suggestion
This is a [Next.js](https://nextjs.org/) project. If you want to know more about Babitz, you can read the checkout the [main project repo](https://github.com/pesto-students/babitz)).
```

2021-07-24 14:09 UTC, chirgjn commented on README.md
> +Also refer to **[Contribution guideline](/CONTRIBUTING.md)** there you will find all the necessary information regarding the how to create file, write and structure code for this project feel free to
```suggestion
Please refer to **[Contribution guideline](/CONTRIBUTING.md)**. You will find all the necessary information regarding the how to create file, write and structure code for this project. Feel free to contribute, suggestion for changes in the guidelines are also welcomed.
```

2021-07-25 07:27 UTC, chirgjn approved these changes

2021-07-25 07:41 UTC, chirgjn commented
@siddanand can you add a comment for the final commit message here in the required format

2021-07-25 08:28 UTC, siddanand commented
Add link to the main repo

2021-07-25 09:17 UTC, chirgjn commented
> @siddanand can you add a comment for the final commit message here in the required format

@siddanand

2021-07-25 09:27 UTC, siddanand commented
> > @siddanand can you add a comment for the final commit message here in the required format
> 
> @siddanand

Added link to the main repo

2021-07-25 10:03 UTC, siddanand commented
docs: add link to main repo

2021-07-25 10:14 UTC, siddanand commented
### docs : update README 
- Add link to the main repo
- Add to setup and run project
- Remove learn more and deploy to vercel
- Add want to contribute section

2021-07-25 10:15 UTC, siddanand commented
### docs : update README
- Add link to the main repo
- Add how to setup and run project
- Remove learn more and deploy to Vercel
- Add want to contribute section

2021-07-25 10:59 UTC, merged